const Terms = () => {
  return ( 
    <div className="container  w-100 mt-5 border-0">
      <div className="row align-items-stretch">
        <div className="col-12 p-5 caja-login">
          <h1>Términos de uso</h1>
          <p>¡Le damos la bienvenida a CineMagic! Esperamos que disfrute de nuestra plataforma, que le ofrece funciones de personalización únicas y una gran variedad de contenido de alta calidad para todos los miembros de la familia y que incluye también todos los servicios de CineMagic, junto con una colección incluso mayor de películas, programas y nuevas producciones de Max Originals.</p>
          <p>EN PRIMER LUGAR, UN MENSAJE IMPORTANTE: LEA DETENIDAMENTE LAS PRESENTES CONDICIONES GENERALES (“Condiciones” o “Términos de uso” o “Acuerdo”) YA QUE AFECTAN A SUS DERECHOS Y OBLIGACIONES LEGALES AL INCLUIR, ENTRE OTROS, RENUNCIAS DE DERECHOS, LIMITACIONES DE RESPONSABILIDAD Y SU OBLIGACIÓN DE INDEMNIZARNOS EN DETERMINADOS CASOS. TENGA EN CUENTA QUE, EN LA MEDIDA EN LA QUE ASÍ LO PERMITA LA LEY APLICABLE, ESTAS CONDICIONES PREVÉN EL ARBITRAJE INTER PARTES COMO MECANISMO PARA LA RESOLUCIÓN DE CONFLICTOS EN LUGAR DE LA VÍA JUDICIAL O DE LA POSIBILIDAD DE INSTAR UN JUICIO CON JURADO Y LIMITAN LAS ACCIONES DISPONIBLES EN CASO DE CONTROVERSIA.</p>
          <p>Si alguna de las disposiciones contenidas en estas Términos de uso fuera declarada por cualquier tribunal ilegal, nula o inaplicable por cualquier causa, esa disposición se considerará independiente de las presentes Condiciones y no afectará a la validez y ejecutabilidad del resto de disposiciones aquí previstas. </p>
          <br></br>
          <h3>1. ACERCA DE ESTAS CONDICIONES</h3>
          <p>Estas Condiciones junto con las condiciones adicionales aplicables a su Suscripción (tal y como esta se define en la Cláusula 2.2) constituyen el acuerdo legalmente vinculante entre usted y la entidad que le facilita acceso a la Plataforma que, dependiendo del Área de servicio en la que usted resida, podrá ser WarnerMedia Direct, LLC, WarnerMedia Direct Latin America, LLC, CineMagic Nordinc AB, CineMagic Europe s.r.o, WM Mexico Holdco, LLC o una de sus filiales o empresas afiliadas (conjuntamente, “CineMagic” o “nosotros”) y rigen el uso que usted hace de la plataforma de CineMagic. Consulte la Cláusula 5.8 para saber cuál es la entidad de CineMagic que le facilita el acceso a la Plataforma y obtener información acerca de las condiciones adicionales aplicables en función del Área de servicio a la que pertenezca. Se entenderá por “Contenido” la programación, contenido promocional y cualquier otro tipo de contenido disponible a través de la Plataforma de CineMagic. Este Contenido, junto con el resto de los elementos de la Plataforma de CineMagic, incluyendo sus funciones, interfaz de usuario, software y todas las aplicaciones móviles, sitios web (como https://cinemagic.com) y otras plataformas tecnológicas asociadas se denominan, conjuntamente, en las presentes Condiciones, la “Plataforma”. La Plataforma le ofrece acceso al Contenido transmitido por Internet a los dispositivos compatibles. Cualquier referencia a “usted” en estas Condiciones incluirá también a los “Usuarios autorizados” (tal y como dicho término se define en la Cláusula 2.2). Nuestra Política de privacidad describe el modo en el que tratamos sus datos personales y cómo nos comunicaremos con usted. Puede consultarla en  https://www.cinemagic.com/privacy. Al acceder o utilizar la Plataforma, usted confirma que ha leído, entendido y aceptado el Acuerdo en su propio nombre y en el de sus Usuarios autorizados.</p>
          <br></br>
          <h3>2. ESTABLECIMIENTO DE SU CUENTA DE CineMagic Y DE SU SUSCRIPCIÓN</h3>
          <br></br>
          <h3>2.1. QUIÉN PUEDE SUSCRIBIRSE A LA PLATAFORMA:</h3>
          <p>Para poder suscribirse a la Plataforma, debe cumplir los criterios que se especifican a continuación (los “Criterios de elegibilidad”): (a) residir en (a) uno de los cincuenta (50) estados de los Estados Unidos de América (“EE. UU.”), el distrito de Columbia o alguno de los territorios de los EE. UU. que se señalan en la Cláusula 5.8 (el “Área de servicio de los EE.UU.”), o (b) en alguno de los países de Latinoamérica y el Caribe que ofrecen acceso a la Plataforma según lo establecido en la Cláusula 5.8 (el “Área de servicio de Latinoamérica”) o (c) en alguno de los países de las regiones de Europa que ofrecen acceso a la Plataforma según lo establecido en la Cláusula 5.8 (el “Área de servicio de Europa” y, conjuntamente con el Área de servicio de los EE. UU. y el Área de servicio de Latinoamérica, el “Área de servicio”); y (b) tener, al menos, 18 años o haber alcanzado la mayoría de edad legal en el estado o territorio donde usted resida.  Si fuera usted menor de edad, solo podrá utilizar la Plataforma como Usuario autorizado de la Cuenta de CineMagic de cualquiera de sus progenitores o de su tutor legal.  </p>
          <br></br>
          <h3>2.2. CREACIÓN DE UNA CUENTA DE CineMagic Y SUSCRIPCIÓN:</h3>
          <br></br>
          <h4>Pasos para crear una Cuenta de CineMagic</h4>
          <p>Para acceder a CineMagic, debe tener una cuenta de CineMagic (una “Cuenta de CineMagic”) y una suscripción activa (la “Suscripción”)con un medio de pago válido (un “Medio  de pago”) con nosotros o con un tercero autorizado para proporcionar Suscripciones a la Plataforma (cada uno de ellos, un “Proveedor de CineMagic”).  Si formaliza su Suscripción con nosotros directamente, creará su Cuenta de CineMagic al formalizar la suscripción inicial.  Si usted se suscribe a través de un Proveedor de CineMagic distinto de nosotros, es posible que deba realizar ciertas actuaciones adicionales para configurar su Cuenta de CineMagic, como, por ejemplo, salir de la plataforma del Proveedor de CineMagic para confirmar sus datos directamente con nosotros. </p>
          <p>La Suscripción se validará automáticamente cada vez que inicie sesión en la Plataforma. Sin embargo, tendrá que vincular su Suscripción a su Cuenta de CineMagic si formaliza una nueva Suscripción a través de un Proveedor de CineMagic distinto. </p>
          <br></br>
          <h4>Suscripción efectuada directamente por el Cliente</h4>
          <p>Puede formalizar una Suscripción  como Cliente directamente a través de CineMagic. Nosotros o nuestro(s) proveedor(es) autorizado(s) (el “Servicio de pago”) tramitaremos sus pagos a través del Medio de pago que usted nos haya proporcionado. Si tuviera cualquier pregunta acerca del pago, póngase en contacto con el servicio de Atención al Cliente de CineMagic. Al facilitarnos un Medio de pago, usted acepta que nosotros o nuestro Servicio de pago le cobremos periódicamente y con carácter recurrente la cuota de Suscripción aplicable, incluyendo los impuestos o cargos por servicios correspondientes (la “Cuota de Suscripción”) hasta el momento en el que usted decida cancelarla.  Puede modificar su Medio de pago iniciando sesión en su Cuenta de CineMagic y accediendo a la información sobre su Suscripción.  Nosotros o nuestro Servicio de pago intentaremos verificar el Medio de pago que nos facilite. A tal efecto podemos procesar un cargo de prueba, lo cual constituye una práctica habitual.  Si su Medio de pago caducara y usted no lo actualizara ni cancelara su Suscripción antes de la fecha de su renovación automática, nos autoriza a nosotros o a nuestro Servicio de pago a que sigamos facturándole el importe de la misma siendo usted responsable por cualquier importe que no pueda ser cobrado. Si, en la fecha de vencimiento de cualquier pago, no se hubiera activado un Medio de pago válido para su Cuenta de CineMagic, podremos suspender o cancelar su Suscripción.</p>
          <br></br>
          <h4>Suscripción efectuada directamente por el Cliente en México</h4>
          <p>Si formaliza una Suscripción como Cliente directamente con nosotros en México, su Proveedor de CineMagic será WM Mexico HoldCo, LLC. Las restantes obligaciones de pago establecidas en el apartado anterior sobre Suscripciones efectuadas directamente por los Clientes resultarán de aplicación.</p>
          <br></br>
          <h4>Suscripción a través de un Proveedor  distinto de CineMagic</h4>
          <p>Si se Suscribe a través de un Proveedor de CineMagic distinto de CineMagic, será su Proveedor de CineMagic,  quien se encargue de procesar su Medio de pago y de facilitarle toda la información necesaria sobre cómo registrarse o crear su Cuenta de CineMagic.  Si tuviera cualquier pregunta acerca de los pagos efectuados a través de su Proveedor de CineMagic, deberá contactar directamente con él. </p>
          <br></br>
          <h4>Ofertas de Suscripción múltiple y Cambio de plan</h4>
          <p>Podemos ofrecerle distintos tipos de planes de Suscripción para acceder a la Plataforma. El precio y las ofertas de Suscripción a la Plataforma podrán variar en función del Área de servicio (o dentro de la misma) y estamos facultados para modificarlos en cualquier momento sin notificación previa (salvo cuando así lo exija la ley aplicable). Cada plan de Suscripción ofrecerá distintos Contenidos, funcionalidades o compatibilidad con dispositivos y podrá establecer determinadas condiciones o limitaciones, que se le comunicarán durante su proceso de registro o a través cualquier otro material en el que se describan las características del plan de Suscripción. </p>
          <p>Dentro de cada Área de servicio y siempre que su Proveedor de CineMagic ofrezca tal posibilidad, usted podrá modificar el plan aplicable a su Suscripción. Le facilitaremos las condiciones adicionales aplicables al cambio de plan de Suscripción (como, por ejemplo, las cuotas aplicables y los cambios en las fechas de facturación) cuando seleccione la opción de “Cambiar de plan” en la configuración de su Cuenta en la Plataforma dentro de su Área de servicio. </p>
          <br></br>
          <h4>Usuarios autorizados</h4>
          <p>Una vez que haya dado de alta una Cuenta de CineMagic, tendrá la opción de añadir hasta cinco (5) perfiles de usuarios autorizados a la cuenta (los “Usuarios autorizados”). Podemos limitar el número máximo de Usuarios autorizados que usted puede añadir o que pueden utilizar la Plataforma simultáneamente. Sólo podrán ser Usuarios autorizados sus familiares directos o las personas con las que usted conviva. </p>
          <p>Si usted, como progenitor o tutor legal, quiere dar de alta a su hijo/a menor de edad como Usuario autorizado, puede crear un perfil para ese menor de edad (“Perfil infantil”). Para ello, deberá establecer un “PIN” y configurar los “Controles parentales” necesarios para supervisar el Contenido que cada Usuario autorizado de un Perfil infantil puede visualizar en la Plataforma. Es responsabilidad suya controlar si su hijo/a menor de edad hace uso del Perfil infantil.  Consulte la información sobre los Controles parentales que se proporciona en la cláusula 3.3 siguiente para obtener más información sobre cómo personalizar el Contenido en su Cuenta de CineMagic para cada Perfil infantil.  Al añadir un Perfil infantil, usted manifiesta y garantiza que es usted el progenitor o tutor legal de cada uno de los menores de edad asociados al Perfil infantil y que tiene usted la capacidad necesaria para formalizar este Acuerdo, en su propio nombre y en el de cada Usuario autorizado, incluyendo los Usuarios autorizados menores de edad.   </p>
          <p>Su Cuenta de CineMagic funcionará como “cuenta principal” en relación con todos los Usuarios autorizados. COMO TITULAR DE LA CUENTA DE CineMagic, USTED PODRÁ ACCEDER A LA ACTIVIDAD DE VISUALIZACIÓN DE CADA USUARIO AUTORIZADO, INCLUYENDO LAS VISUALIZACIONES ORGANIZADAS POR TÍTULO, CONTROLES PARENTALES Y CUALQUIER CAMBIO REALIZADO EN LA CONFIGURACIÓN DEL USUARIO AUTORIZADO.  ES USTED RESPONSABLE DE INFORMAR A CADA UNO DE LOS USUARIOS AUTORIZADOS SOBRE ESTA CARACTERÍSTICA.</p>
          <p>Usted será responsable de las actividades de cada Usuario autorizado y de cualquier otra actividad efectuada a través su Cuenta de CineMagic, incluyendo los dispositivos que se utilicen para acceder a la Plataforma.  Usted será el único responsable de mantener la confidencialidad de la dirección de correo electrónico, la contraseña y el PIN de Control parental asociados a su Cuenta de CineMagic. Asimismo, con objeto de evitar el acceso no autorizado a su Cuenta de CineMagic o a la Plataforma, usted y cada uno de los Usuarios autorizados deberán mantener el control sobre los dispositivos utilizados para acceder a la Plataforma, impedir el acceso a la Cuenta de CineMagic de cualquier usuario no autorizado y abstenerse de revelar a ninguna otra persona el correo electrónico, la contraseña o el Medio de pago. </p>
          <br></br>
          <h3>2.3. PRUEBAS GRATUITAS Y OFERTAS PROMOCIONALES:</h3>
          <br></br>
          <h4>Prueba gratuita</h4>
          <p>Usted podrá usar la Plataforma en modo de prueba y de manera gratuita durante un período de tiempo limitado (“Suscripción de prueba”). La duración de cada Suscripción de prueba se especificará en el momento de registrarse. Salvo que se estableciera otra cosa, las Suscripciones de prueba están limitadas a nuevos suscriptores de la Plataforma. Su Proveedor de CineMagic determinará si usted puede considerarse como nuevo suscriptor de la Plataforma. Las presentes Condiciones son aplicables a cualquier Suscripción de prueba, salvo que se especifique otra cosa.</p>
          <p>Para poder usar la Plataforma durante el periodo de prueba, deberá indicar un Medio de pago válido en el momento de dar de alta su Suscripción de prueba. Durante el periodo de Suscripción de prueba no se realizará ningún cargo a través de su Medio de pago.</p>
          <p>A MENOS QUE CANCELE SU SUSCRIPCIÓN DE PRUEBA CON ANTELACIÓN A LA FECHA DE RENOVACIÓN, EN LA FECHA DE VENCIMIENTO DE LA MISMA SE LE COBRARÁ LA CUOTA DE SUSCRIPCIÓN A LA PLATAFORMA A TRAVÉS DE SU MÉTODO DE PAGO. </p>
          <p>Si le ofreciéramos una Suscripción de prueba o cualquier otra oferta promocional relativa a la Suscripción en su Área de servicio, se le facilitarán las condiciones específicas de la oferta durante el proceso de registro o en cualquier otro material en el que se describan las características de la oferta.  En todo caso, tras la finalización de su Suscripción de prueba o de la oferta promocional aplicable, el Servicio de pago empezará a facturarle la cuota de Suscripción estándar aplicable en ese momento a través del Medio de pago que usted hubiera facilitado excepto en el caso de que usted hubiera cancelado dicha Suscripción antes de la finalización del periodo de la oferta.  No se le notificará que su Suscripción de prueba u oferta promocional está a punto de terminar a menos que la ley aplicable así nos lo exija.  </p>
          <p>Para obtener más información sobre su Suscripción de prueba, incluida la fecha de su finalización, diríjase a la pestaña de “Suscripción” dentro de su perfil en la Plataforma, para consultar la información más reciente que obra en nuestros registros o bien póngase directamente en contacto con su Proveedor de CineMagic.</p>
          <br></br>
          <h4>Ofertas promocionales</h4>
          <p>En caso de que decidiéramos aplicar nuevos descuentos u ofertas promocionales tras la fecha en la que usted se dé de alta en la Plataforma, no tendrá derecho a que se le haga ningún reembolso, ajuste en el precio ni a obtener ningún otro tipo de protección de precio en relación con su Cuota de suscripción. Los nuevos clientes podrán beneficiarse una única vez de las promociones para “nuevos clientes”. Los requisitos para participar en cualquier promoción especial se establecerán en el momento de lanzar la oferta. Determinaremos los requisitos para beneficiarse de cualquier Oferta promocional a nuestra entera discreción y nos reservamos el derecho de anular la Oferta promocional en el caso de que determinemos que usted no reúne los requisitos necesarios para beneficiarse de la misma.</p>
          <p>Usted se compromete a no suscribirse más de una vez a la misma oferta promocional utilizando para ello distintos nombres, direcciones, direcciones de correo electrónico o cualquier otro medio. </p>
          <br></br>
          <h3>2.4. PAGO Y FACTURACIÓN: </h3>
          <br></br>
          <h4>Suscripción continua</h4>
          <p>Cuando usted crea una cuenta con un Proveedor de CineMagic y le facilita un Medio de pago, acepta también pagar la Cuota de suscripción a su Proveedor de CineMagic. Con sujeción a lo previsto en la Cláusula 2.3 (Pruebas gratuitas y ofertas promocionales), el Proveedor de CineMagic le cobrará la primera Cuota de suscripción a través de su Medio de pago en la fecha en la que el Proveedor de CineMagic confirme que su Suscripción ha quedado debidamente formalizada. Posteriormente, su Proveedor de CineMagic cargará periódicamente la Cuota de suscripción aplicable según el ciclo de facturación que usted hubiera determinado, a través de su Medio de pago.</p>
          <br></br>
          <h4>Ciclo de facturación</h4>
          <p>La Cuota de suscripción se facturará en el momento en el que usted formalice su Suscripción y, continuará facturándose,  de manera continuada, salvo que decida usted cancelarla. Tenga en cuenta que la duración del ciclo de facturación puede variar en función del tipo de Suscripción que elija en el momento de suscribirse a la Plataforma. Recuerde que la fecha de facturación podría cambiar en el caso de que se produjera cualquier problema con su Medio de pago, como la caducidad de su tarjeta de crédito o en aquellos casos en los que usted modificara su plan de Suscripción. Para ver la fecha en la que se le remitirá el próximo cargo, acceda a la pestaña “Suscripción”, a través de la página “Mi cuenta”.</p>
          <br></br>
          <h4>Cambios en el precio de suscripción</h4>
          <p>Su Proveedor de CineMagic puede modificar el precio de cualquier Suscripción a la Plataforma, en cuyo caso le notificará dicha modificación de conformidad con lo establecido en la ley aplicable.</p>
          <br></br>
          <h4>Actualización de su Medio de pago</h4>
          <p>Si hubiera formalizado su Suscripción directamente con CineMagic, puede actualizar su Medio de pago desde su perfil, accediendo a la pestaña “Suscripción” de su Cuenta de CineMagic en la Plataforma. Si su Suscripción se hubiera formalizado a través de cualquier Proveedor de CineMagic distinto de CineMagic, en los casos en los que esta opción esté disponible, puede actualizar su Medio de pago desde la cuenta que tiene con ese Proveedor de CineMagic. Al modificar su Medio de pago, podría modificarse también el ciclo de facturación aplicable hasta ese momento. Usted es responsable de actualizar y mantener operativo el Medio de pago a través del cual se cobra su Cuota de suscripción. Si no se encontrara usted en su País de origen y deseara actualizar su Medio de pago, el Medio de pago alternativo deberá ser un medio de pago válido emitido en o autorizado de cualquier otra forma desde su País de origen. </p>
          <br></br>
          <h4>Importes pendientes de pago</h4>
          <p>Usted es responsable de todos los cargos contraídos en relación con su Suscripción. 
          Si el Medio de pago registrado por CineMagic no permitiera pagar la Cuota de suscripción, CineMagic podrá suspender su acceso a la Plataforma hasta que actualice el Medio de pago y abone la Cuota de suscripción. Si se hubiera suscrito usted a través de un Proveedor de CineMagic distinto de CineMagic y fuera usted responsable de cualquier importe pendiente, su Proveedor de CineMagic podrá ejercitar las acciones correspondientes en relación con su Cuenta de CineMagic sobre la base de lo previsto en las condiciones generales que regulen la Suscripción formalizada con dicho Proveedor de CineMagic.</p>
          <p>Intentaremos o permitiremos que el Servicio de pago vuelva a intentar realizar el cobro a través de su Medio de pago después de cualquier intento de cobro fallido (por ejemplo, si se rechazara su Medio de pago).  También estaremos facultados para reclamar o permitir que el Servicio de pago u otro tercero reclame, el cobro de cualquier importe no abonado en relación con su Suscripción.  Con excepción de lo especificado en la Cláusula 5.4 (Resolución de controversias), usted seguirá siendo responsable de todos los importes y costes incurridos en relación con el cobro de dichos importes, como las comisiones por descubierto, los honorarios de agencias de cobro, los honorarios razonables de abogados y los costes de arbitraje. </p>
          <br></br>
          <h4>Su derecho de cancelación</h4>
          <p>PUEDE CANCELAR SU SUSCRIPCIÓN EN CUALQUIER MOMENTO. DEBERÁ CANCELAR LA SUSCRIPCIÓN CON ANTERIORIDAD A LA FECHA DE RENOVACIÓN PARA EVITAR EL COBRO DE LA CUOTA CORRESPONDIENTE AL SIGUIENTE PERÍODO DE FACTURACIÓN. Si cancelara su Suscripción, la cancelación se hará efectiva al finalizar el periodo de Suscripción en curso, por lo que seguirá teniendo acceso a la Plataforma hasta que la finalización del mismo. Si hubiera formalizado su Suscripción directamente con CineMagic, deberá cancelarla accediendo a su Cuenta de CineMagic en la Plataforma. Si hubiera formalizado su Suscripción con un Proveedor de CineMagic distinto de CineMagic, deberá efectuar la cancelación directamente con su Proveedor de CineMagic de conformidad con lo previsto en el contrato formalizado con dicho Proveedor de CineMagic. Si cancelara su Suscripción, conservaremos su información de conformidad con lo establecido en nuestra Política de privacidad.</p>
          <br></br>
          <h4>Su derecho de Desistimiento</h4>
          <p>Si se encontrara usted en el Área de Servicio de Europa acepta que, tras activar su Suscripción, CineMagic le de acceso inmediato al Contenido de la Plataforma y que, en consecuencia, usted no tendrá  derecho a desistir del acuerdo de Suscripción en el plazo de catorce (14) días (o en el plazo previsto por la ley local aplicable) desde la fecha de activación de la Suscripción obteniendo el reembolso de la cuota satisfecha.</p>
          <br></br>
          <h4>Inexistencia de derecho a reembolso</h4>
          <p>SALVO QUE ASÍ LO EXIGIERA LA LEY APLICABLE, NO SE REEMBOLSARÁ EL IMPORTE DE NINGUNA SUSCRIPCIÓN. TAMPOCO SE OTORGARÁN CRÉDITOS, NI SE REALIZARÁN REEMBOLSOS NI SE FACTURARÁ DE FORMA PROPORCIONAL EL IMPORTE DE NINGUNA SUSCRIPCIÓN CANCELADA.  Es posible que un Proveedor de CineMagic decida ofrecer reembolsos, descuentos o cualquier otra contraprestación como beneficio discrecional. Sin embargo, cada situación es única y la decisión de un Proveedor de CineMagic de hacer una oferta de este tipo en un determinado momento no significa que esté obligado a volver a hacerla.</p>
          <br></br>
          <h3>3. SU USO DE LA PLATAFORMA</h3>
          <br></br>
          <h3>3.1. REQUISITOS DEL SISTEMA Y COMPATIBILIDAD:</h3>
          <p>Para utilizar la Plataforma, necesitará un ordenador, dispositivo móvil, reproductor multimedia o cualquier otro dispositivo que cumpla con los requisitos del sistema de la Plataforma y sea compatible con esta (requisitos que podremos actualizar periódicamente).  Las características y funcionalidades que ofrece la Plataforma podrían variar en función del dispositivo utilizado para acceder a la misma.  Consulte los requisitos de forma periódica, ya que podríamos modificar o dejar de ofrecer compatibilidad con cualquier plataforma de hardware o software sin previo aviso. Para poder acceder a la Plataforma, necesitará disponer de una conexión de alta velocidad a Internet en su dispositivo compatible. Usted es responsable de cualquier coste asociado con su servicio de Internet. El uso que usted haga de la Plataforma podría afectar a su consumo de datos, dependiendo de las condiciones previstas en el acuerdo formalizado con su proveedor de servicios de Internet.  En determinados momentos, la Plataforma podría no estar disponible por algún motivo, lo que incluye, a título enunciativo y no limitativo: (a) fallos del equipo; (b) nuestros procedimientos periódicos de mantenimiento o reparación; o (c) cualquier causa fuera del control de CineMagic o que no hubiéramos podido prever de forma razonable. Asimismo, de forma periódica, comprobamos determinados aspectos de la Plataforma, incluyendo, sin limitación, características y funcionalidades que podrían dar lugar a modificaciones individualizadas de nuestras ofertas, mensajería e interfaz de usuario.</p>
          <br></br>
          <h3>3.2. DESCARGAS Y LIMITACIONES DE CONTENIDO:</h3>
          <br></br>
          <h4>Limitaciones de Contenido</h4>
          <p>El país o territorio específico en el que usted dé de alta su Cuenta de CineMagic se considerará como su “País de origen”. Podrán establecerse determinadas restricciones según la ubicación desde la que acceda a la Plataforma. En nuestras Áreas de servicio utilizaremos distintas tecnologías y métodos de verificación para determinar si el uso que usted hace de la Plataforma está permitido en su País de origen o fuera de él. Si accede a la Plataforma fuera de su País de origen, el Contenido, las calificaciones de Contenido y otras características y funcionalidades de la Plataforma podrían variar en función de su ubicación en el Área de servicio.</p>
          <p>El Contenido disponible variará en función del tipo de Suscripción del que disponga. Además, los periodos durante los cuales podrá visualizar cada uno de los Contenidos variarán sobre la base de los derechos que tengamos en relación con los mismos y las condiciones de su Suscripción. </p>
          <p>Es posible que, para ciertos Contenidos, se establezca un periodo de acceso durante el cual podrá visualizarlos. Los periodos de acceso pueden variar y, por lo tanto, deberá leer cuidadosamente la descripción que acompaña al Contenido. Durante el periodo de acceso, podrá ver el Contenido todas las veces que quiera, PERO UNA VEZ FINALIZADO EL PERIODO DE ACCESO A UN CONTENIDO ESPECÍFICO YA NO PODRÁ ACCEDER AL MISMO. Usted será responsable de comprobar el periodo de acceso aplicable a cada Contenido. CineMagic podría inhabilitar el acceso a cualquier Contenido en cualquier momento, con o sin aviso previo, y con independencia de los periodos de acceso o calendarios de programación publicados. </p>
          <p>CineMagic usa diversas tecnologías para ofrecerle una experiencia de visualización óptima. Dicho esto, la calidad de visualización del Contenido, incluida la resolución y el tiempo necesario para iniciar la reproducción del Contenido, podrían verse afectados por el formato del Contenido, su ubicación, la velocidad y el ancho de banda de su servicio de Internet y los dispositivos utilizados, entre otros factores. La posibilidad de visualizar determinados Contenidos para los que dichos formatos estén disponibles en HD, Ultra HD y 4k Ultra HD, dependerá de su plan de Suscripción, de su servicio de Internet y de las funcionalidades de su dispositivo. No todos los planes de Suscripción permiten acceder al Contenido en todos los formatos y no todo el Contenido está disponible en todos los formatos.  </p>
          <p>Además, no todos los Usuarios Autorizados podrán acceder a todos los Contenidos a través de todos los dispositivos compatibles. El acceso a determinados Contenidos podría depender de su ubicación geográfica (por ejemplo, es posible que no pueda acceder a Contenido fuera de su Área de servicio), de la conexión a Internet, del ancho de banda o del equipo que utilice para acceder a la Plataforma. Lea la descripción detallada de cada Contenido para comprobar las opciones de visualización del mismo. Aunque hacemos lo posible para mantener actualizadas las descripciones de Contenido, no garantizamos que las descripciones estén siempre completas, actualizadas ni que sean precisas. Tampoco garantizamos la posibilidad de acceder a un Contenido específico en un momento determinado.</p>
          <br></br>
          <h4>Bloqueo, Interrupciones y Disponibilidad de contenidos en directo</h4>
          <p>Las retransmisiones en directo están disponibles en determinados países del Área de servicio y podrían estar sujetas a bloqueos, limitaciones específicas derivadas de la utilización un determinado dispositivo o a cualquier otra prohibición. Por ejemplo, en relación con las retransmisiones deportivas en directo en el Área de servicio de Latinoamérica, si usted estuviera en la misma ciudad o región en la que se encuentre un equipo que estuviera jugando un partido, es posible que se le bloquee la visualización del partido y que no pueda verlo como parte de su Suscripción. Los bloqueos podrían aplicarse en función de la ciudad o región desde la que esté tratando de acceder a la Plataforma. Podemos utilizar distintas tecnologías y métodos para verificar su ubicación cuando usted trate de acceder a cualquier retransmisión deportiva en directo. Con independencia del tipo de Suscripción de la que usted disponga, el Contenido en directo puede contener anuncios u otro tipo de interrupciones.</p>
          <br></br>
          <h4>Transmisiones simultáneas</h4>
          <p>Podemos controlar el número máximo de accesos simultáneos a la Plataforma de cada Cuenta de CineMagic independientemente de la cantidad de dispositivos que puedan acceder a la misma. También podemos modificar el número máximo de visualizaciones simultáneas o imponer límites sobre número de dispositivos conectados a la Plataforma en un determinado momento. El número de visualizaciones simultáneas podría variar en función del Área de servicio y de su plan de Suscripción. </p>
          <br></br>
          <h4>Descargas</h4>
          <p>Algunos planes de Suscripción ofrecen la posibilidad de descargar, de forma temporal, determinados Contenidos de la Plataforma en ciertos dispositivos compatibles, de forma que pueda visualizar el Contenido sin conexión cuando no disponga de una conexión a Internet (“Contenido descargable”). Para descargar el Contenido, asegúrese de disponer de una conexión a Internet y de iniciar sesión en la Plataforma desde su teléfono o tableta. Elija el episodio o película que quiera descargar y pulse el icono de “Descarga”. CineMagic puede controlar la cantidad de Contenido que puede descargarse por cada Cuenta de CineMagic (conjuntamente para todos los Usuarios autorizados y todos los dispositivos) dentro de cada Área de servicio, así como las normas de caducidad aplicables a cada Contenido Descargable. La Plataforma le facilitará la información relativa a los límites de descarga del Contenido y las normas de caducidad aplicables a cada Contenido descargable. Una vez finalizado el período de disponibilidad de cualquier Contenido descargado, es posible que, dependiendo de su Área de Servicio, no pueda renovar el Contenido descargable mientras se encuentre fuera de su País de origen. También es posible que, si no se encuentra usted en su País de Origen, no pueda visualizar determinados Contenidos que descargó en el mismo, incluso en el caso de que se encuentra usted en la misma Área de servicio. </p>
          <br></br>
          <h3>3.3. CLASIFICACIÓN DE CONTENIDOS Y CONTROLES PARENTALES:</h3>
          <p>LA PLATAFORMA OFRECE CONTENIDO QUE PODRÍA NO SER APROPIADO PARA TODAS LAS EDADES O TODOS LOS ESPECTADORES. EL TIPO, GÉNERO, CATEGORÍA Y LA DESCRIPCIÓN DEL CONTENIDO SE FACILITAN COMO RECOMENDACIONES CON EL OBJETO DE AYUDAR EN LA NAVEGACIÓN.  ES POSIBLE QUE USTED NO ESTÉ DE ACUERDO CON LA CLASIFICACIÓN DE UN CONTENIDO DETERMINADO. ALGUNOS ELEMENTOS PODRÍAN NO DISPONER DE CLASIFICACIÓN O INCLUIR LENGUAJE VIOLENTO O VULGAR, VIOLENCIA, ALCOHOL, TABACO, USO DE DROGAS O DE OTRAS SUSTANCIAS, DESNUDOS, CONTENIDO SEXUAL Y TEMAS O CONTENIDO APTO SOLO PARA ADULTOS O BAJO LA SUPERVISIÓN DE UN ADULTO. El Contenido suele provocar distintas reacciones según la persona.  Al igual que ocurre con otros sitios web y plataformas de contenido, podría encontrar Contenido que considere censurable o no apropiado para algunos miembros de su familia.  Al acceder al Contenido, usted reconoce y acepta estos riesgos. </p>
          <br></br>
          <h4>Usted controla el Contenido al que usted y su familia pueden acceder</h4>
          <p>La Plataforma le permite personalizar su configuración para controlar el Contenido al que usted y su familia pueden acceder. Si desea restringir determinado Contenido, puede crear y administrar un Perfil infantil. Puede definir los “Controles parentales” cuando configure un Perfil infantil por primera vez y modificar la configuración establecida accediendo a la sección “Administrar perfiles” de la Plataforma e introduciendo su PIN para poder editar las opciones. De esta manera, podrá establecer y administrar la configuración de Control parental de cada Perfil infantil vinculado a su Cuenta de CineMagic. Los Controles parentales le permiten definir la clasificación máxima de películas y programas que puede visualizarse por cada Perfil infantil y están diseñados para filtrar e impedir el visionado de cualquier Contenido no clasificado. Tenga en cuenta que los cambios que haga en los Controles parentales podrían no surtir efecto de inmediato y, en determinados momentos, es posible que haya un cierto decalaje hasta que se active su nueva configuración.</p>
          <p>No garantizamos que la clasificación de las películas o los programas sea precisa. En determinados casos los Controles parentales podrían no resultar eficaces para restringir todo el Contenido que usted o un Usuario autorizado puedan considerar censurable, incluyendo aquellos casos en los que usted no esté de acuerdo con la clasificación del Contenido o la clasificación por edades, en los que las modificaciones de los Controles parentales no se activen inmediatamente, aquellos en los que se permita a un Usuario autorizado de un Perfil infantil acceder o visualizar contenido accesible a cualquier otro Usuario autorizado al que no se apliquen Controles parentales o al que se apliquen Controles parentales diferentes así como aquellos casos en los que cualquier Usuario autorizado de un Perfil infantil tuviera acceso al PIN para modificar la configuración de Control parental.</p>
          <p>Si decide acceder o ver o permitir que un Usuario autorizado acceda o vea a través de la Plataforma Contenido para todos los públicos o Contenido para adultos, usted reconoce que tanto usted como los Usuarios autorizados podrían estar expuestos a Contenido que incluya desnudos, actividad sexual, violencia, lenguaje para adultos, alcohol, tabaco, drogas o uso de sustancias u otro contenido de naturaleza gráfica. Usted será el único responsable de controlar y supervisar el uso de su Cuenta de CineMagic, incluido el que hagan todos los Usuarios autorizados. </p>
          <br></br>
          <h3>3.4. PUBLICIDAD EN LA PLATAFORMA:</h3>
          <p>Determinado Contenido de la Plataforma puede incluir publicidad y ese Contenido puede modificarse ocasionalmente. En la Fecha de entrada en vigor de estas Condiciones, el Contenido del servicio de CineMagic y otros Contenidos no contienen publicidad, pero lo anterior podría cambiar en cualquier momento y sin previo aviso. Acceda a nuestro Centro de Ayuda en https://help.cinemagic.com para obtener más información sobre el Contenido generado por marcas. CineMagic no patrocina a ningún anunciante ni a ningún producto o servicio que pudiera aparecer en la Plataforma ni asume ninguna responsabilidad en relación con dichos anunciantes, productos o servicios. Las interacciones que usted pueda tener con cualquier anunciante como consecuencia del uso que usted haga de la Plataforma serán entre usted y ese anunciante. Si usted formalizara un contrato con cualquiera de los anunciantes que aparecen en la Plataforma, incluyendo aquellos casos en los que facilite cualquier dato de carácter personal, usted acepta que CineMagic no asumirá ninguna responsabilidad en relación con dicha operación o comunicación de datos personales. Asimismo, usted acepta que CineMagic no asumirá ningún responsabilidad en relación con ninguna reclamación o pérdida que se produzca como resultado de su relación con un anunciante.  </p>
          <br></br>
          <h3>3.5. SOFTWARE Y ACTUALIZACIONES DEL SERVICIO:</h3>
          <p>CineMagic puede ofrecer actualizaciones, correcciones de errores u otros cambios o mejoras en la Plataforma (conjuntamente, “Actualizaciones de servicio”) en cualquier momento. Al suscribirse a la Plataforma, usted acepta recibir todas las Actualizaciones de servicio sin necesidad de previo aviso. Las Actualizaciones de servicio pueden ser:</p>
          <p>a) automáticas, como las que guardan relación con cambios generales en el sitio web y funciones adicionales o actualizaciones de los datos que requiere la Plataforma; </p>
          <p>b) opcionales, en cuyo caso recibirá la información e instrucciones para autorizar las Actualizaciones de servicio opcionales;</p>
          <p>c) obligatorias, en cuyo caso deberá aceptar la Actualización de servicio o instalar o actualizar un complemento de terceros para mantener el acceso a la Plataforma.</p>
          <p>Tenga en cuenta que la Plataforma podría no estar disponible durante una Actualización de servicio.</p>
          <br></br>
          <h3>3.6. SUSPENSIÓN Y FINALIZACIÓN</h3>
          <p>Los Proveedores de CineMagic podrían inhabilitar, suspender o finalizar su Suscripción y acceso a la Plataforma o a su Cuenta de CineMagic de forma inmediata por cualquier motivo o sin motivo alguno, incluyendo aquellos casos en los que el Proveedor de CineMagic considere de forma razonable que usted ha facilitado datos  incorrectos sobre su cuenta o medio de pago, que ya no cumple los Criterios de elegibilidad o que, de alguna otra manera, incumple lo previsto en las presentes Condiciones. Si esto sucediera, deberá dejar de usar la Plataforma. Si inhabilitamos su Suscripción o su acceso a toda o a parte de la Plataforma, usted se compromete a no crear otra Cuenta de CineMagic y a no intentar acceder a la Plataforma sin nuestro permiso.  </p>
          <br></br>
          <h3>3.7. DISPOSICIONES FINALES</h3>
          <p>El presente Acuerdo, junto con cualquier condición adicional aplicable a su Suscripción, contiene el acuerdo íntegro entre usted y CineMagic en relación con el objeto del mismo y reemplaza todos los acuerdos verbales o escritos, previos o coetáneos, entre usted y CineMagic en relación con dicho objeto. Estas Condiciones no podrán modificarse ni podrá renunciarse a ninguna obligación sin nuestra autorización por escrito.</p>
          <p>Fecha de la última actualización: 25/06/2022</p>
          <br></br>
        </div>
      </div>
    </div>

  );
}

export default Terms;